### ISSUE TITLE
Add support for pods

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [marhkb/pods#127]
Currently, there is no way to tell if a container is part of a pod. It would be nice if containers were grouped by pod, or if there was a separate page (like Images and Containers) for pods. There should also be ways to interact with a pod, like starting, stopping or pausing it.

**Comment by NoTuxNoBux** [comment]
To take this slightly further, it would be nice if logs from all containers in the pod can also be shown in the pod logs tab. Combined with #139 and #140, it would make it easier to see all logs your applications send. I'm currently just doing this through the terminal.

**Comment by marhkb** [comment]
Thanks for working on this. 
Everything that the log crates produces goes directly into syslog. The intention was not to lose logs on rare crashes, make the logs more discoverable, etc. 
I would like to plan to redirect all the remaining output to syslog as well, but haven't yet looked into it.

You can follow the logs with `journalctl _COMM=pods -f`

**Comment by marhkb** [comment]
Basic support for pods has been implemented now
- Creating new pods (by now just with a name and hostname)
- Listing pods
- Showing pod details
- Controlling a pod's state (start, pause, resume, stop, ...)
- Creating containers inside pods
- Showing processes inside a pod

Everything that is still missing should be tracked in separate issues.
