### ISSUE TITLE
Translations not used (?)

### ISSUE THREAD

**Issue by Gert-dev** [marhkb/pods#150]
Hi

Is there a possibility that translations aren't actually working yet :sweat_smile: ? As you might remember I added a Dutch translation a couple of weeks ago, and updated to the latest Flatpak some days ago, but it's still defaulting to English for me. I also use other Flatpak applications such as Lollypop and these translate fine.

My active locale is `nl_BE.UTF-8`, which I think should fall back correctly to the `nl.po`, or am I missing something and does it need to be called `nl_BE.po`?

Thanks!

**Comment by marhkb** [comment]
Yeah, that's a problem I also encounter. I have the same problem with [Telegrand](https://github.com/melix99/telegrand]) where I contribute and asked this in their Telegram group. It seems that the problem is well known. Someone suggested setting the `LANG` variable, but that has no effect for me.

> I also use other Flatpak applications such as Lollypop and these translate fine.

It seems there is something different with flathub distributed apps. But I have not figured out, yet. I tested running gnome-calendar from source and also encounter missing translations.

I am quite confident that the language files work correctly for native builds as seen is this [comment](https://github.com/marhkb/pods/issues/99#issuecomment-1081763656)

But I have no idea why it does not work for the flatpak.

**Comment by marhkb** [comment]
@Gert-dev 
It works for me when I export a bundle (Bundle exportieren) and install that.

![Bildschirmfoto von 2022-04-11 10-53-04](https://user-images.githubusercontent.com/3630213/162701099-5384ad29-4381-43e3-8a55-f5cee0770def.png)

The German translation is quite incomplete now, but it says "Konfiguriert".

![Bildschirmfoto von 2022-04-11 10-52-17](https://user-images.githubusercontent.com/3630213/162701412-12a1030f-cc82-451e-941c-e03196ad08ae.png)

**Comment by Gert-dev** [comment]
@marhkb Is it possible that [it is already being built and exported](https://docs.flatpak.org/en/latest/flatpak-builder.html#exporting-to-a-repository) but it's not being distributed yet through the Flatpak I download from GitHub? Most of the Flathub Flatpaks such as Lollypop have a separate `org.gnome.Lollypop` have a separate `org.gnome.Lollypop.Locale` extension that seems to handle localization. According to the above link, this extension is automatically built, so perhaps it's simply not part of the download from the artifacts that GitHub Actions delivers?

**Comment by marhkb** [comment]
https://github.com/bilelmoussaoui/flatpak-github-actions/issues/46

**Comment by marhkb** [comment]
The latest builds seem to use the correct translation for me. So, the problem somehow has solved itself.

Feel free to re-open if it's not the case for you.

**Comment by Gert-dev** [comment]
For me it seems to have had no effect, unfortunately. I installed the Flatpak generated from the latest commit (https://github.com/marhkb/pods/commit/47900338526199b0fe17d3cc563c3984f3935908), and just tried starting the application - I verified it's the latest build, but it's still in English for me (though perhaps it's misdetecting the language)?

**Comment by marhkb** [comment]
You're correct. I was quite sure it was working. But after trying again, it is all English again no matter which language I try.

**Comment by 0xMRTT** [comment]
We got the same problem in https://github.com/GradienceTeam/Gradience/issues/107

**Comment by Gert-dev** [comment]
@marhkb I think this can be closed since Pods is on Flathub Beta now, where the problem no longer exists - the `.Locale` package is automatically proposed for installation and translations work for me there.
