### ISSUE TITLE
arabic translation

### ISSUE THREAD

**Issue by allaeddineomc** [marhkb/pods#168]
I'm currently working on the Arabic translations , i need to hear how your name is pronounced to be able to write it in Arabic letters

**Comment by marhkb** [comment]
Marcus [ˈmaʁkʊs]
Behrendt [ˈbeɹɛnt`]

It comes quite close If you copy `ˈmaʁkʊs ˈbeɹɛnt` to http://ipa-reader.xyz/ and choose `Marlene (German)` as speaker.

**Comment by allaeddineomc** [comment]
done
