### ISSUE TITLE
Flathub Beta submission

### ISSUE THREAD

**Issue by Eonfge** [marhkb/pods#300]
Cool to see all the projects focussing on Podman. Yesterday I was checking out Podman Desktop, and to day I stumbled upon your project.

While trying it out, I was wondering if you could add your project to Flathub. Now, I understand that you don't consider your application ready for prime-time, but Flathub also has a beta-channel that might be perfect way for you to get the app in the hands of testers.

If you need any help submitting your app to Flathub, feel free to ask me for help. I maintain a multitude of packages so I'll gladly help.

**Comment by marhkb** [comment]
Thanks for your help. That has already brought me further. I think I'll do without automatic deployment for now and create manual pre-release versions on Github, which will then be published on Flathub Beta. Maybe that can be addressed later when I'm more familiar with all the processes.

> The biggest challenge would be, to parse the rust-dependency list into a Flatpak specced list of reproducible resources. Since you can't download resources while building (that would break reproducibility) you must have a file that dictates all resources before.

I haven't thought about that at all. :-) For that, I will take the `vendor` script, which is already in `build-aux` dir (from the rust-template). Have seen that this is the standard procedure of many rust projects like [Kooha](https://github.com/flathub/io.github.seadve.Kooha).

### What is still not so clear to me:
The [submission instructions](https://github.com/flathub/flathub/wiki/App-Submission) describe the steps to submit a new app.

Unfortunately, the instructions not handle submissions for Flathub Beta. How exactly do I communicate that I only want to do beta releases? Is the newly created repository empty, or does it already contain my PR as the first commit on the master branch? That would be exactly what I want to avoid, wouldn't it?

**Comment by marhkb** [comment]
https://github.com/flathub/flathub/pull/3483

**Comment by Eonfge** [comment]
Sorry for not having the time to reply. I was rather busy, and my Steam Deck came in so I had my mind elsewhere. 

Seems that you've been quite far in your submission. The biggest issue that might come up right now, is that you're not building from source.

**Comment by Eonfge** [comment]
`home/kevin/Projects/flatpak-builder-tools/cargo/flatpak-cargo-generator.py ./Cargo.lock -o cargo-sources.json`

File that contains all the sources, using the flatpak-cargo-generator
[cargo-sources.zip](https://github.com/marhkb/pods/files/9542242/cargo-sources.zip)

Interesting idea... you could add this file to your pre-commit hooks, so that every time you push to git, you add a full list of resources for Flatpak.

**Comment by marhkb** [comment]
Thanks for your help. The PR has been accepted. For now, I plan to push manual updates to the beta channel.
