### ISSUE TITLE
add ability to create containers as root

### ISSUE THREAD

**Issue by allaeddineomc** [marhkb/pods#408]
root containers have useful abilities like binding to port 80 , it will be great if such containers can be created in pods

**Comment by marhkb** [comment]
This should already be possible. You can just start the podman system service as root.
For example
``` sh
# podman system service --time=0 tcp://0.0.0.0:8082
```
And then connect 
![grafik](https://user-images.githubusercontent.com/3630213/198898068-cea41722-93e7-4cea-9aa2-2b8dc7bdbc2a.png)

You then can create and run containers with port 80 on the host.

![grafik](https://user-images.githubusercontent.com/3630213/198906158-ff9eae20-630c-4df5-9c22-51bbf4b99c78.png)


Alternatively, one could start the podman systemd service as root, but it seems at least on fedora normal users have no read access to `/run/podman/podman.sock` by default.

**Comment by allaeddineomc** [comment]
yes this works but it requires starting the tcp service everytime the user wants to activate this connection , i will se if there is a way to make /run/podman/podman.sock readable , running pods as root didn't work when trying to use /run/podman/podman.sock which is weird

**Comment by marhkb** [comment]
Yeah, for example, you can enable rootful in cockpit-podman. But as cockpit-podman is running as a root systemd service, it has no problems accessing `/run/podman/podman.sock`.
No idea how to proceed here with flatpak.

> yes this works but it requires starting the tcp service everytime the user wants to activate this connection

I think you could automate that with a systemd service.

> running pods as root didn't work when trying to use /run/podman/podman.sock

Can you reach it through `curl`? If you can reach it, you should also maybe give the flatpak file system permissions.

**Comment by marhkb** [comment]
There are now instructions in the app on how to connect to the root Podman instance. I think this is acceptable for now until someone figures out a way to make it easier.
