### ISSUE TITLE
Mention somewhere how to activate podman socket

### ISSUE THREAD

**Issue by philn** [marhkb/pods#437]
On first run of the app the user needs to add a "Connection" but there is a lack of context about this in the UI. I had to look it up since on my system the socket wasn't activated by default:

```
systemctl --user start podman.socket
```

**Comment by philn** [comment]
Maybe link to https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md#socket-activation-of-the-api-service

**Comment by marhkb** [comment]
Thanks for reporting!
