### ISSUE TITLE
Relatively long time needed to load (images and contaiers) on startup

### ISSUE THREAD

**Issue by NoTuxNoBux** [marhkb/pods#458]
Not sure how much of this is Pods' fault or perhaps podman's, but I noticed that Pods takes relatively long to get the list of images and containers loaded on startup.

After start-up, it takes around ~40 seconds of the loading spinner showing before the overview is filled. I only have about 10 images and 30 containers present currently. Perhaps it is iterating each entry in the list, executing a command per item?

Would be happy to execute some raw podman commands if desired to see if that is also slow.

### Reproduction steps
- Start up the application with about 10 images and 30 containers.
- Observe slow loading times.

### Environment

- Pods version: 1.0.0-beta.9
- Podman version: 4.3.1

**Comment by marhkb** [comment]
Yeah, this seems to be a problem with the socket. It shouldn't take that long when there are only 30 images (I don't think it wouldn't take that long even with thousands of images). You could try to restart it.
```
$ systemctl --user restart podman.socket
```
As a last resort, you could try to restart your computer.
If nothing works, you should definitely open a bug report in the podman repo.

Reopen this if you are able to reduce the time of the curl command, but Pods takes still too long to load.
