### ISSUE TITLE
Create a colorful graphic for an illustration placeholder page 

### ISSUE THREAD

**Issue by marhkb** [marhkb/pods#465]
GNOME [HIG](https://developer.gnome.org/hig/patterns/feedback/placeholders.html) describes the concept of illustration placeholder page.

![grafik](https://user-images.githubusercontent.com/3630213/206923263-ae2b3c55-b3a5-4700-aeb5-e01fd165bdbc.png)

Pods is currently lacking a colorful graphics that is the prerequisite to have such an illustration placeholder page.
Thus, this issue is about to create such a colorful graphic.

Currently, the first page of Pods looks rather sad.
![grafik](https://user-images.githubusercontent.com/3630213/206923762-e77d960c-bc11-4e87-bf89-244c1f04367c.png)

Personally, I like the style of GNOME Tour
![grafik](https://user-images.githubusercontent.com/3630213/206923514-61594c9e-75f3-4c29-904b-2c849e75fadb.png)
![grafik](https://user-images.githubusercontent.com/3630213/206924004-e530fea7-15bc-473e-bd62-5eb0e424ad39.png)
![grafik](https://user-images.githubusercontent.com/3630213/206924029-d96c3d35-306d-4775-a186-fca17de4bf8d.png)

**Comment by daudix-UFO** [comment]
What about something like this?

![welcome](https://user-images.githubusercontent.com/77155297/209211700-4cd81ec5-5d6f-4cf5-8dec-ab278b922941.png)

**Comment by marhkb** [comment]
This looks excellent. But I think there are two places that would not play nice with the light theme. Maybe they nee some darker colors?

![remarks](https://user-images.githubusercontent.com/3630213/209226052-873252fd-b768-432e-a038-29efb22f0a02.png)

**Comment by daudix-UFO** [comment]
Tweaked the colors a bit

![welcome](https://user-images.githubusercontent.com/77155297/209229772-465f2bae-57cf-44ea-ae15-8048463202dd.png)

**Comment by daudix-UFO** [comment]
[welcome-pods.zip](https://github.com/marhkb/pods/files/10290518/welcome-pods.zip)

**Comment by marhkb** [comment]
That looks really great (PR https://github.com/marhkb/pods/pull/491).

![grafik](https://user-images.githubusercontent.com/3630213/209239020-ee179c56-2c00-49f5-bf3f-94a52d8bfc7e.png)

![grafik](https://user-images.githubusercontent.com/3630213/209239056-4ac73631-45be-4d9c-943e-19e11cd92052.png)

**Comment by marhkb** [comment]
@daudix-UFO I think this is ready to land. But I decided to remove the QR code on the packet since the picture scales down when shrinking the window and that was making it blurry. It is very noticeable in this specific place and would disturb this very beautiful illustration.

After removing the QR code I saved the file as an "optimized svg", is this correct? Is there anything else I have to consider?

**Comment by daudix-UFO** [comment]
Optimized SVG is pretty good, but it will be better to save as regular inkscape SVG and then optimize it using [svgo](https://github.com/svg/svgo), I have done this for you ;)

[welcome-pods.zip](https://github.com/marhkb/pods/files/10296949/welcome-pods.zip)

**Comment by marhkb** [comment]
Merged. Thank you very much. It's looking great.
