### ISSUE TITLE
Return to creation wizard and restore user data on creation errors

### ISSUE THREAD

**Issue by tiritto** [marhkb/pods#478]
When you try to create a new Container you're asked to provide all details like memory limits, port mapping, volumes and environmental variables etc. This is great. Then if something goes with your setup you receive an error with notification, which is what you would expect as well.

However, at this point your only option is to close the notification window and start the process all over again, which depending on complexity of your configuration might be very annoying and tedious, especially for newcomers but might also happen to more advanced user due to simple spelling errors.

I believe that the best way to handle this issue with user experience in mind is to keep all data provided by the user until operation is confirmed to be successful. Otherwise, allow user to go Back to creation wizard without losing the data they already filled in.

**Comment by marhkb** [comment]
Thanks for reporting. Yes, the problem you describe is indeed annoying.
Now it should be fixed for the first case (right after you set the settings). For the next version, I plan to solve it also for the second case (action window is opened by clicking on the corresponding notification entry). But this is not technically possible at the moment and thus needs some more work.
