### ISSUE TITLE
Only a few lines of logs are being displayed

### ISSUE THREAD

**Issue by marcinjahn** [marhkb/pods#521]
### Reproduction steps

Run container trhat produces logs, in my case it's a mountebank image.
The screenshot below shows that there are many lines of logs in the terminal, while Pods shows just a few of them:

![image](https://user-images.githubusercontent.com/10273406/214272912-5a279865-ae97-4f5c-8545-3dfd514a57f1.png)

### Environment

- Pods version: 1.0.2

**Comment by marhkb** [comment]
Thanks for reporting.
An attempt to fix this is implemented in #522. Could you try that out? You can just grab it from [here](https://github.com/marhkb/pods/actions/runs/4009302199), if you are a flatpak user.

**Comment by marcinjahn** [comment]
It works as it should now, thanks!
