### ISSUE TITLE
I'm missing the option to use a docker/podman volume instead of a filesystem binding

### ISSUE THREAD

**Issue by hyperspace01** [marhkb/pods#558]
When creating a container I want to be able to use a volume to store some data of the container. However, Pods only show the option for a filesystem binding. Is this something I need to configure, or is this feature missing?

![image](https://user-images.githubusercontent.com/39904003/216822612-2c88a312-2157-42ce-81d5-bc76a4a52007.png)

**Comment by marhkb** [comment]
Depends on #563
