### ISSUE TITLE
Back button/swipe to go back

### ISSUE THREAD

**Issue by Vinnl** [marhkb/pods#597]
#### Describe your feature request

My mouse has two buttons on the side that I use to go back and forward in the browser, and on my trackpad, I swipe to the right to go back in the browser. It would be nice if I could do the same to go back to the list after inspecting an image/a container in Pods.

**Comment by marhkb** [comment]
I just tested and it works already. Every `AdwLeaflet` in Pods has set [can-navigate-back](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.2/property.Leaflet.can-navigate-back.html) property. 

From the property's description:
> Whether gestures and shortcuts for navigating backward are enabled.
> The supported gestures are: One-finger swipe on touchscreens
>
> - One-finger swipe on touchscreens
> - Horizontal scrolling on touchpads (usually two-finger swipe)
> - Back/forward mouse buttons

[Bildschirmaufzeichnung vom 2023-03-26, 23-14-24.webm](https://user-images.githubusercontent.com/3630213/227805023-5cecb00e-a1df-401c-989d-887111db0dba.webm)

Can you specify exactly where it is not working?

**Comment by Vinnl** [comment]
Hmm. I swear it didn't work before! But you're right, they do work now, weird :/

I'll close this issue then, thanks for the great app, it's working really well for me!
