### ISSUE TITLE
Unable to connect to unix socket

### ISSUE THREAD

**Issue by dnkmmr69420** [marhkb/pods#610]
### Reproduction steps

Click unix socket option
Type this in the terminal
`systemctl --user enable --now podman.socket`
press connect
says no such file or directory

### Environment

- Pods version: 1.1.0 (latest at the time of this report)

**Comment by marhkb** [comment]
Thanks for reporting. I need more information to solve this

1. What Distro?
2. Installation Method. Native or Flatpak?
3. What's your podman version?
4.  Attach logs: `journalctl _COMM=pods > pods.log` and post here
5. What's the output of `curl --unix-socket /run/user/${UID}/podman/podman.sock  http://d/v4.0.0/libpod/info`?

**Comment by dnkmmr69420** [comment]
It was fixed. I didn't see the link to the [documentation](https://github.com/containers/podman/blob/cea9340242f3f6cf41f20fb0b6239aa3db5decd6/docs/tutorials/socket_activation.md)
