### ISSUE TITLE
When you press the lightbulb icon setting up a connection during the first setup, you can't exit it.

### ISSUE THREAD

**Issue by dnkmmr69420** [marhkb/pods#612]
### Reproduction steps
Download pods from flathub
set it up
press the lightbulb icon
try to click away to close the popup
you are unable to do it

### Environment

- Pods version: 1.1.0 latest pods version at the time

**Comment by marhkb** [comment]
Hi. I tried to reproduce this on wayland, X11 and XWayland. Unfortunately, I wasn't able to see the error. So I have no idea what could be causing this.

[Bildschirmaufzeichnung vom 2023-04-08, 20-01-01.webm](https://user-images.githubusercontent.com/3630213/230736227-5560777d-38db-487a-9f85-2ff289930b2d.webm)

**Comment by dnkmmr69420** [comment]
that is quite weird

**Comment by dnkmmr69420** [comment]
it doesn't happen anymore so I guess it solved itself
