### ISSUE TITLE
Can't create file at /run/systemd/journal/socket: No such device or address

### ISSUE THREAD

**Issue by muzammil786** [marhkb/pods#657]
I have the issue with running Pods via flatpak:

```
flatpak run com.github.marhkb.Pods
bwrap: Can't create file at /run/systemd/journal/socket: No such device or address
```

The dir exists

```
[root@RHEL8u6 engineer]# ll /run/systemd/journal/socket
srw-rw-rw-. 1 root root 0 Mar  3 18:50 /run/systemd/journal/socket
```

What do you think is the problem?

**Comment by marhkb** [comment]
Thanks for reporting this.

This is indeed weird. I can reproduce it on a Debian machine. What's your flatpak version? On Debian it is 1.10.8. Maybe it's a flatpak bug?

As a workaround you can install [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) and just remove the `/run/systemd/journal/socket` permission. The application will run, but wil not produce logs.

![Bildschirmfoto vom 2023-05-11 19-12-09](https://github.com/marhkb/pods/assets/3630213/0bdcc3b0-7a32-4dc3-9776-a33f875c7699)

**Comment by marhkb** [comment]
This issue is now pinned.
