### ISSUE TITLE
Romanian language (RO) is missing from the built package

### ISSUE THREAD

**Issue by SoftExpert** [marhkb/pods#677]
Hello, frustrated translator here ;-)

Despite being 100% done for several months already and having the PO file in the build folder, the Romanian language is actually not deployed / used.

I also noticed that the file [LINGUAS](https://github.com/marhkb/pods/tree/main/po/LINGUAS) does not declare **ro**.

Any idea why and how this could be resolved?

### Reproduction steps
Build and use Pods while setting the context to display in Romanian.

### Environment
All

Thank you in advance for your help !

**Comment by marhkb** [comment]
Thanks for the report. :-)

> I also noticed that the file [LINGUAS](https://github.com/marhkb/pods/tree/main/po/LINGUAS) does not declare ro.

I think you found the solution here. No idea, why it wasn't in there...

**Comment by marhkb** [comment]
I've released 1.2.1. Maybe you can give it a try.

**Comment by marhkb** [comment]
Hmm, it's still not there.
