### ISSUE TITLE
Add support for privileged containers

### ISSUE THREAD

**Issue by bellegarde-c** [marhkb/pods#752]
Here on Silverblue, containers do not run without --privileged flag.

Should be useful to have this option while creating a container.

**Comment by marhkb** [comment]
@bellegarde-c Could you try the artifact from https://github.com/marhkb/pods/actions/runs/7103547131

**Comment by bellegarde-c** [comment]
@marhkb Works as expected :)

**Comment by bellegarde-c** [comment]
Deployed on my IT infrastructure, this will really help students managing containers :)
