### ISSUE TITLE
Add support for SSH scheme

### ISSUE THREAD

**Issue by 0x454d505459** [marhkb/pods#783]
#### Describe your feature request
I would be great if pods was able to use ssh to connect to a server, or directly integrate with the podman connections already saved.

For instance I use this string to connect to my remote podman instance
`ssh://podmanctrler@192.168.1.102:22/run/user/1000/podman/podman.sock` which works with podman but not pods: `Provided scheme ssh is not supported`

**Comment by marhkb** [comment]
This is currently not possible with the underlying podman library. See https://github.com/vv9k/podman-api-rs/issues/142.

A workaround could be to run podman under a port on the remote machine and then use a ssh tunnel on the local machine.

**Comment by 0x454d505459** [comment]
Well that's pretty unfortunate, I guess this works just as well, despite being a hacky fix.

Closing this issue as fixed, it may get reopened once podman-api-rs supports ssh (or just podman's connection system).

Thanks

**Comment by woodsb02** [comment]
Rather than making the user manually set up an SSH tunnel with port forwarding, could the podman-desktop app provide a GUI to do that for them?
