### ISSUE TITLE
Can I view my Root-user pods with Pods?

### ISSUE THREAD

**Issue by cyangalaxy** [marhkb/pods#794]
Hey, sorry to disturb again.

I made this issue here: https://github.com/marhkb/pods/issues/793

I realized that I need my specific pods to be system-installed (Root user).

Can I manage my system-installed pods with Pods? Can I somehow grant Pods access to those? It's only seeing user-installed pods.

The Podman doc is complicated

Kind regards.

**Comment by marhkb** [comment]
GH Discussions is the proper place for such questions.
