### ISSUE TITLE
New release needed because rust `1.80.0`

### ISSUE THREAD

**Issue by DerRockWolf** [marhkb/pods#797]
Because of an unfixable build regression in rust `1.80.0`, building pods `2.0.1` is currently broken.  
Building from the current main branch works because the `time` crate has been updated in the meantime.

Would it be possible to create a new release, so that we don't need to bump to an unstable commit in https://github.com/NixOS/nixpkgs/pull/335565 ?

See [NixOS/nixpkgs#332957](https://togithub.com/NixOS/nixpkgs/issues/332957) & [rust-lang/rust#127343](https://togithub.com/rust-lang/rust/issues/127343) for more details.

Thanks for developing pods :heart:

**Comment by marhkb** [comment]
This took some more effort than expected: https://github.com/marhkb/pods/pull/799

**Comment by DerRockWolf** [comment]
Thanks :heart: 

I'll update to `2.0.2` in nixpkgs.
