### ISSUE TITLE
Possibility of running without Podman service

### ISSUE THREAD

**Issue by Gert-dev** [marhkb/pods#82]
Hello

I was wondering if it was a conscious choice of requiring the Podman service to be running? I often use Podman, and am aware that this service exists since a while ago, but always thought one of the main benefits of Podman was that it, unlike Docker, could be used daemonless (if the service can be called that), so I've never used the service before.

Most of the information I can see in the screenshots is also available from the CLI commands that don't require the daemon, but I understand that it might be easier to talk to the daemon, as it probably uses a more exchangeable format suitable for interaction with external tools?

Thanks!

**Comment by marhkb** [comment]
To the best of my knowledge, no native API exists - at least not for rust. But I could be wrong about that.
The bottom line is that in the future, it should be possible to connect to remote Podman instances. And at this point at the latest, I would need the RESTful API that is exposed through the service anyway.

**Comment by Gert-dev** [comment]
Thanks for your response.

> The bottom line is that in the future, it should be possible to connect to remote Podman instances. And at this point at the latest, I would need the RESTful API that is exposed through the service anyway.

That makes sense. Executing commands will be harder in that case without having an SSH connection or similar to be able to execute Podman commands on the remote system.

FWIW, Podman CLI commands do have the possibility to output JSON, e.g. `podman images --format json`, but I understand that supporting two approaches to talk to the same piece of software might not be worth the hassle.

**Comment by marhkb** [comment]
#203 is currently WIP to connect to different (remote) Podman services. Parsing command line output seems not really feasible for that task.
So, I'm closing this now as the RESTful API seems the most reasonable approach, which is also used by cockpit-podman btw.
