### ISSUE TITLE
Add option to show old container list UX

### ISSUE THREAD

**Issue by deadmeu** [marhkb/pods#828]
#### Describe your feature request
The new containers UX takes up a lot of space. I would like the option to revert back to the old list design as it is more space efficient and makes it easier to start/restart/stop multiple containers in sequence.

**Comment by JoseBritto** [comment]
To add to this, in the new UI I'm unable to see the full container names if the name is a bit on the longer side, making it difficult to differentiate.
![image](https://github.com/user-attachments/assets/526688fe-841c-4076-b585-2aaac1d4076c)

**Comment by marhkb** [comment]
Switching layouts is planned for the next release.

**Comment by M2tec** [comment]
Good to hear this is being worked on. Looking forward to next release. I am a big offender in long container names. It's hard right now. Love the app. 
![image](https://github.com/user-attachments/assets/6799f2c3-d7ce-4812-b86e-7c2a22c17e8b)
