### ISSUE TITLE
List if connected service is running as root or as user

### ISSUE THREAD

**Issue by rohmishra** [marhkb/pods#84]
With podman one can either run podman service and container as either root or as rootless - from their own account.

Currently there is no way to easily find out which method is being used. A visual indicator to differentiate would be nice.

Coloring the headerbar like in Kings Cross Terminal would be strong and simple indictor but any indictor even if its just a tag would be welcome.

**Comment by marhkb** [comment]
Yes, that's on the TODO list. In the long run, it should be possible to make the Podman instance configurable for the user. As soon as this is possible, it should be displayed to which Podman instance one is currently connected.
At the moment, it is always assumed to communicate with the user service (rootless).

**Comment by wcasanova** [comment]
something similar to cockpit-podman, I attach a reference image, it can also be used for cpu and memory statistics.
![imagen](https://user-images.githubusercontent.com/12401985/159355269-ee76b2cc-a17f-4096-a4aa-ffd7389d9044.png)
in my case, just activate the podman socket as user
